<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['en' => 'Afghan', 'ar' => 'أفغاني'],
            ['en' => 'Albanian', 'ar' => 'ألباني'],
            ['en' => 'Algerian', 'ar' => 'جزائري'],
            ['en' => 'American', 'ar' => 'أمريكي'],
            ['en' => 'Andorran', 'ar' => 'أندوري'],
            ['en' => 'Angolan', 'ar' => 'أنغولي'],
            ['en' => 'Argentine', 'ar' => 'أرجنتيني'],
            ['en' => 'Armenian', 'ar' => 'أرميني'],
            ['en' => 'Australian', 'ar' => 'أسترالي'],
            ['en' => 'Austrian', 'ar' => 'نمساوي'],
            ['en' => 'Azerbaijani', 'ar' => 'أذربيجاني'],
            ['en' => 'Bahamian', 'ar' => 'باهامي'],
            ['en' => 'Bahraini', 'ar' => 'بحريني'],
            ['en' => 'Bangladeshi', 'ar' => 'بنجلاديشي'],
            ['en' => 'Barbadian', 'ar' => 'باربادوسي'],
            ['en' => 'Belarusian', 'ar' => 'بيلاروسي'],
            ['en' => 'Belgian', 'ar' => 'بلجيكي'],
            ['en' => 'Belizean', 'ar' => 'بليزي'],
            ['en' => 'Beninese', 'ar' => 'بنيني'],
            ['en' => 'Bhutanese', 'ar' => 'بوتاني'],
            ['en' => 'Bolivian', 'ar' => 'بوليفي'],
            ['en' => 'Bosnian', 'ar' => 'بوسني'],
            ['en' => 'Brazilian', 'ar' => 'برازيلي'],
            ['en' => 'British', 'ar' => 'بريطاني'],
            ['en' => 'Bruneian', 'ar' => 'بروني'],
            ['en' => 'Bulgarian', 'ar' => 'بلغاري'],
            ['en' => 'Burkinabe', 'ar' => 'بوركيني'],
            ['en' => 'Burundian', 'ar' => 'بوروندي'],
            ['en' => 'Cambodian', 'ar' => 'كمبودي'],
            ['en' => 'Cameroonian', 'ar' => 'كاميروني'],
            ['en' => 'Canadian', 'ar' => 'كندي'],
            ['en' => 'Cape Verdean', 'ar' => 'رأس أخضري'],
            ['en' => 'Central African', 'ar' => 'وسط أفريقي'],
            ['en' => 'Chadian', 'ar' => 'تشادي'],
            ['en' => 'Chilean', 'ar' => 'تشيلي'],
            ['en' => 'Chinese', 'ar' => 'صيني'],
            ['en' => 'Colombian', 'ar' => 'كولومبي'],
            ['en' => 'Comoran', 'ar' => 'قمري'],
            ['en' => 'Congolese', 'ar' => 'كونغولي'],
            ['en' => 'Costa Rican', 'ar' => 'كوستاريكي'],
            ['en' => 'Croatian', 'ar' => 'كرواتي'],
            ['en' => 'Cuban', 'ar' => 'كوبي'],
            ['en' => 'Cypriot', 'ar' => 'قبرصي'],
            ['en' => 'Czech', 'ar' => 'تشيكي'],
            ['en' => 'Danish', 'ar' => 'دنماركي'],
            ['en' => 'Djiboutian', 'ar' => 'جيبوتي'],
            ['en' => 'Dominican', 'ar' => 'دومينيكاني'],
            ['en' => 'Dutch', 'ar' => 'هولندي'],
            ['en' => 'East Timorese', 'ar' => 'تيموري شرقي'],
            ['en' => 'Ecuadorian', 'ar' => 'إكوادوري'],
            ['en' => 'Egyptian', 'ar' => 'مصري'],
            ['en' => 'Emirati', 'ar' => 'إماراتي'],
            ['en' => 'Equatoguinean', 'ar' => 'غيني استوائي'],
            ['en' => 'Eritrean', 'ar' => 'إريتري'],
            ['en' => 'Estonian', 'ar' => 'إستوني'],
            ['en' => 'Ethiopian', 'ar' => 'إثيوبي'],
            ['en' => 'Fijian', 'ar' => 'فيجي'],
            ['en' => 'Finnish', 'ar' => 'فنلندي'],
            ['en' => 'French', 'ar' => 'فرنسي'],
            ['en' => 'Gabonese', 'ar' => 'غابوني'],
            ['en' => 'Gambian', 'ar' => 'غامبي'],
            ['en' => 'Georgian', 'ar' => 'جورجي'],
            ['en' => 'German', 'ar' => 'ألماني'],
            ['en' => 'Ghanaian', 'ar' => 'غاني'],
            ['en' => 'Greek', 'ar' => 'يوناني'],
            ['en' => 'Grenadian', 'ar' => 'غرينادي'],
            ['en' => 'Guatemalan', 'ar' => 'غواتيمالي'],
            ['en' => 'Guinean', 'ar' => 'غيني'],
            ['en' => 'Guyanese', 'ar' => 'غياني'],
            ['en' => 'Haitian', 'ar' => 'هايتي'],
            ['en' => 'Honduran', 'ar' => 'هندوراسي'],
            ['en' => 'Hungarian', 'ar' => 'مجري'],
            ['en' => 'Icelandic', 'ar' => 'آيسلندي'],
            ['en' => 'Indian', 'ar' => 'هندي'],
            ['en' => 'Indonesian', 'ar' => 'إندونيسي'],
            ['en' => 'Iranian', 'ar' => 'إيراني'],
            ['en' => 'Iraqi', 'ar' => 'عراقي'],
            ['en' => 'Irish', 'ar' => 'أيرلندي'],
            ['en' => 'Italian', 'ar' => 'إيطالي'],
            ['en' => 'Ivorian', 'ar' => 'إيفواري'],
            ['en' => 'Jamaican', 'ar' => 'جامايكي'],
            ['en' => 'Japanese', 'ar' => 'ياباني'],
            ['en' => 'Jordanian', 'ar' => 'أردني'],
            ['en' => 'Kazakhstani', 'ar' => 'كازاخستاني'],
            ['en' => 'Kenyan', 'ar' => 'كيني'],
            ['en' => 'Kiribati', 'ar' => 'كيريباتي'],
            ['en' => 'Kuwaiti', 'ar' => 'كويتي'],
            ['en' => 'Kyrgyzstani', 'ar' => 'قيرغيزستاني'],
            ['en' => 'Laotian', 'ar' => 'لاوسي'],
            ['en' => 'Latvian', 'ar' => 'لاتفي'],
            ['en' => 'Lebanese', 'ar' => 'لبناني'],
            ['en' => 'Lesotho', 'ar' => 'ليسوتو'],
            ['en' => 'Liberian', 'ar' => 'ليبيري'],
            ['en' => 'Libyan', 'ar' => 'ليبي'],
            ['en' => 'Liechtensteiner', 'ar' => 'ليختنشتايني'],
            ['en' => 'Lithuanian', 'ar' => 'ليتواني'],
            ['en' => 'Luxembourger', 'ar' => 'لوكسمبورغي'],
            ['en' => 'Macedonian', 'ar' => 'مقدوني'],
            ['en' => 'Malagasy', 'ar' => 'مدغشقري'],
            ['en' => 'Malawian', 'ar' => 'مالاوي'],
            ['en' => 'Malaysian', 'ar' => 'ماليزي'],
            ['en' => 'Maldivian', 'ar' => 'مالديفي'],
            ['en' => 'Malian', 'ar' => 'مالي'],
            ['en' => 'Maltese', 'ar' => 'مالطي'],
            ['en' => 'Marshallese', 'ar' => 'مارشالي'],
            ['en' => 'Mauritanian', 'ar' => 'موريتاني'],
            ['en' => 'Mauritian', 'ar' => 'موريسي'],
            ['en' => 'Mexican', 'ar' => 'مكسيكي'],
            ['en' => 'Micronesian', 'ar' => 'ميكرونيزي'],
            ['en' => 'Moldovan', 'ar' => 'مولدوفي'],
            ['en' => 'Monacan', 'ar' => 'موناكي'],
            ['en' => 'Mongolian', 'ar' => 'منغولي'],
            ['en' => 'Montenegrin', 'ar' => 'مونتينيغري'],
            ['en' => 'Moroccan', 'ar' => 'مغربي'],
            ['en' => 'Mozambican', 'ar' => 'موزمبيقي'],
            ['en' => 'Namibian', 'ar' => 'ناميبي'],
            ['en' => 'Nauruan', 'ar' => 'ناورو'],
            ['en' => 'Nepalese', 'ar' => 'نيبالي'],
            ['en' => 'New Zealander', 'ar' => 'نيوزيلندي'],
            ['en' => 'Nicaraguan', 'ar' => 'نيكاراغواي'],
            ['en' => 'Nigerian', 'ar' => 'نيجيري'],
            ['en' => 'North Korean', 'ar' => 'كوري شمالي'],
            ['en' => 'Norwegian', 'ar' => 'نرويجي'],
            ['en' => 'Omani', 'ar' => 'عماني'],
            ['en' => 'Pakistani', 'ar' => 'باكستاني'],
            ['en' => 'Palauan', 'ar' => 'بالاوي'],
            ['en' => 'Palestinian', 'ar' => 'فلسطيني'],
            ['en' => 'Panamanian', 'ar' => 'بنمي'],
            ['en' => 'Papua New Guinean', 'ar' => 'بابوا غينيا الجديدة'],
            ['en' => 'Paraguayan', 'ar' => 'باراغواي'],
            ['en' => 'Peruvian', 'ar' => 'بيروفي'],
            ['en' => 'Filipino', 'ar' => 'فلبيني'],
            ['en' => 'Polish', 'ar' => 'بولندي'],
            ['en' => 'Portuguese', 'ar' => 'برتغالي'],
            ['en' => 'Qatari', 'ar' => 'قطري'],
            ['en' => 'Romanian', 'ar' => 'روماني'],
            ['en' => 'Russian', 'ar' => 'روسي'],
            ['en' => 'Rwandan', 'ar' => 'رواندي'],
            ['en' => 'Saint Lucian', 'ar' => 'سانت لوسي'],
            ['en' => 'Salvadoran', 'ar' => 'سلفادوري'],
            ['en' => 'Samoan', 'ar' => 'ساموي'],
            ['en' => 'San Marinese', 'ar' => 'سان مارينو'],
            ['en' => 'Saudi', 'ar' => 'سعودي'],
            ['en' => 'Senegalese', 'ar' => 'سنغالي'],
            ['en' => 'Serbian', 'ar' => 'صربي'],
            ['en' => 'Seychellois', 'ar' => 'سيشلي'],
            ['en' => 'Sierra Leonean', 'ar' => 'سيراليوني'],
            ['en' => 'Singaporean', 'ar' => 'سنغافوري'],
            ['en' => 'Slovak', 'ar' => 'سلوفاكي'],
            ['en' => 'Slovenian', 'ar' => 'سلوفيني'],
            ['en' => 'Solomon Islander', 'ar' => 'جزر سليمان'],
            ['en' => 'Somali', 'ar' => 'صومالي'],
            ['en' => 'South African', 'ar' => 'جنوب أفريقي'],
            ['en' => 'South Korean', 'ar' => 'كوري جنوبي'],
            ['en' => 'South Sudanese', 'ar' => 'جنوب سوداني'],
            ['en' => 'Spanish', 'ar' => 'إسباني'],
            ['en' => 'Sri Lankan', 'ar' => 'سريلانكي'],
            ['en' => 'Sudanese', 'ar' => 'سوداني'],
            ['en' => 'Surinamese', 'ar' => 'سورينامي'],
            ['en' => 'Swazi', 'ar' => 'سوازي'],
            ['en' => 'Swedish', 'ar' => 'سويدي'],
            ['en' => 'Swiss', 'ar' => 'سويسري'],
            ['en' => 'Syrian', 'ar' => 'سوري'],
            ['en' => 'Taiwanese', 'ar' => 'تايواني'],
            ['en' => 'Tajikistani', 'ar' => 'طاجيكستاني'],
            ['en' => 'Tanzanian', 'ar' => 'تنزاني'],
            ['en' => 'Thai', 'ar' => 'تايلاندي'],
            ['en' => 'Togolese', 'ar' => 'توغولي'],
            ['en' => 'Tongan', 'ar' => 'تونغي'],
            ['en' => 'Trinidadian', 'ar' => 'ترينيدادي'],
            ['en' => 'Tunisian', 'ar' => 'تونسي'],
            ['en' => 'Turkish', 'ar' => 'تركي'],
            ['en' => 'Turkmen', 'ar' => 'تركماني'],
            ['en' => 'Tuvaluan', 'ar' => 'توفالي'],
            ['en' => 'Ugandan', 'ar' => 'أوغندي'],
            ['en' => 'Ukrainian', 'ar' => 'أوكراني'],
            ['en' => 'Uruguayan', 'ar' => 'أوروغواي'],
            ['en' => 'Uzbekistani', 'ar' => 'أوزبكستاني'],
            ['en' => 'Vanuatu', 'ar' => 'فانواتو'],
            ['en' => 'Venezuelan', 'ar' => 'فنزويلي'],
            ['en' => 'Vietnamese', 'ar' => 'فيتنامي'],
            ['en' => 'Yemeni', 'ar' => 'يمني'],
            ['en' => 'Zambian', 'ar' => 'زامبي'],
            ['en' => 'Zimbabwean', 'ar' => 'زيمبابوي']
        ];

        foreach ($nationalities as $nationality) {
            Nationality::create([
                'name' => [
                    'en' => $nationality['en'],
                    'ar' => $nationality['ar'],
                ]
            ]);
        }
    }
}
